spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dynamoprofile
    username: postgres
    password: ziP@ss
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate.ddl-auto: update
  management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]

logging:
  level:
    org.springframework.boot: error
    org.springframework.security: debug
    org.springframework.security.web: debug
    org.apache.catalina: error
    com.mainul35:
      - info
      - trace
      - debug
      - error