scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: ['localhost:8080', 'localhost:8081']
        labels:
          application: "Dynamo Profile"